#!/bin/bash

# Tashqi ping uchun cron-job.org API sozlash
# Bu script cron-job.org ga avtomatik ro'yxatdan o'tadi

echo "=== Tashqi Ping Sozlash ==="
echo ""
echo "Variant 1: cron-job.org (Tavsiya etiladi)"
echo "1. https://cron-job.org ga kiring"
echo "2. 'Create cronjob' bosing"
echo "3. Title: Sardor Bot Keepalive"
echo "4. URL: http://sardorsoatbot.alwaysdata.net"
echo "5. Schedule: Every 5 minutes"
echo "6. Save"
echo ""
echo "Variant 2: UptimeRobot"
echo "1. https://uptimerobot.com ga kiring"
echo "2. 'Add New Monitor' bosing"
echo "3. Monitor Type: HTTP(s)"
echo "4. URL: http://sardorsoatbot.alwaysdata.net"
echo "5. Monitoring Interval: 5 minutes"
echo "6. Create Monitor"
echo ""
echo "Variant 3: Render.com (Bepul background worker)"
echo "1. https://render.com ga kiring"
echo "2. 'New' -> 'Background Worker'"
echo "3. GitHub repo ulang"
echo "4. Start Command: python3 external_ping.py"
echo "5. Create"
echo ""
echo "=== Hozirgi holat ==="
echo "Bot ishlayapti: http://sardorsoatbot.alwaysdata.net"
echo "Ichki keepalive: ✅ (har 2 minutda)"
echo "Self-ping: ✅ (har 5 minutda)"
echo "Auto-restart: ✅ (har 12 soatda)"
echo "Cron job: ✅ (har 5 minutda)"
echo ""
echo "Tashqi ping qo'shish uchun yuqoridagi variantlardan birini tanlang."
